name: Train Model

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env
        python-version: 3.9

    - name: Install MLflow in environment
      run: |
        conda run -n mlflow-env pip install mlflow

    - name: Run MLflow Project
      run: |
        conda run -n mlflow-env mlflow run MLProject
